export default {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    GET_USER_REQUEST: 'GET_USER_REQUEST',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
    GET_USER_FAILURE: 'GET_USER_FAILURE',
    START_GAME_REQUEST: 'START_GAME_REQUEST',
    START_GAME_SUCCESS: 'START_GAME_SUCCESS',
    START_GAME_FAILURE: 'START_GAME_FAILURE',
    PLAY_CARD_REQUEST: 'PLAY_CARD_REQUEST',
    PLAY_CARD_SUCCESS: 'PLAY_CARD_SUCCESS',
    PLAY_CARD_FAILURE: 'PLAY_CARD_FAILURE',

};
