export default {
    NOT_STARTED: 'NOT_STARTED',
    STARTING: 'STARTING',
    STARTED: 'STARTED',
    START_FAILURE: 'START_FAILURE',
    PLAYING_CARD: 'PLAYING_CARD',
    PLAYED_CARD: 'PLAYED_CARD',
    PLAY_CARD_FAILURE: 'PLAY_CARD_FAILURE',
    CHANGING_ROUND: 'CHANGING_ROUND',
    CHANGE_ROUND_FAILURE: 'CHANGE_ROUND_FAILURE',
    ENDING_GAME: 'ENDING_GAME',
    END_GAME_FAILURE: 'END_GAME_FAILURE',
};
